parameters:
    # Здесь могут быть параметры бандла

services:

    # Конфигурация для всех сервисов  этого файла по умолчанию
    _defaults:

        # Включает механизм автоматической подстановки зависимостей контейнера
        # в ваши сервисы по typehints аргументов конструктора (и экшнов контроллеров)
        # https://symfony.com/doc/current/service_container.html#the-autowire-option
        autowire: true

        # Включает механизм автоконфигурации:
        # сервисам автоматически добавляются теги по имплементируемым интерфейсам
        # https://symfony.com/doc/current/service_container.html#the-autoconfigure-option
        autoconfigure: true 

    # Регистрируем контроллеры бандла и репозиторий как DI-сервисы

    Tlc\ReportBundle\Report\AbstractPdf: ~
    Tlc\ReportBundle\Report\AbstractReport: ~
